version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: autopbusiness
      POSTGRES_PASSWORD: root
      POSTGRES_DB: atb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tojosoavinamaster@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  server-prisma:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-prisma
    image: server
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
    - REDIS_URL=redis://redis:6379/0
    links:
    - redis

    restart: always

  redis:
    image: redis:6.2.5-alpine

volumes:
  postgres-data:
  pgadmin-data: